# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f940d05a730e56f9bb58406f1cb8058bc4b2aff4b6a0657d209742266f237c9bb9ac9cc832d1e73f6febf78b673f7e4dad295f626cae96fb8e3bb37366e6eab

test:
  secret_key_base: 8c96e04f225b05f485d6015b787fccb23fc96d831b9f9fa24a38770b0c15fb6afd0774660f1612e7ca2d28fe51161036ca2556a43394fc4e4e1d681ef44e627e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
